-- MySQL Script generated by MySQL Workbench
-- Mon Mar 26 14:22:25 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema civkac
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema civkac
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `civkac` DEFAULT CHARACTER SET utf8 ;
USE `civkac` ;

-- -----------------------------------------------------
-- Table `civkac`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `civkac`.`user` ;

CREATE TABLE IF NOT EXISTS `civkac`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `email` VARCHAR(60) NOT NULL,
  `image` VARCHAR(300) NOT NULL DEFAULT 'img/defaultUser.png',
  `handle` VARCHAR(20) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `Username_UNIQUE` (`username` ASC),
  UNIQUE INDEX `Email_UNIQUE` (`email` ASC),
  UNIQUE INDEX `handle_UNIQUE` (`handle` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `civkac`.`post`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `civkac`.`post` ;

CREATE TABLE IF NOT EXISTS `civkac`.`post` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `text` VARCHAR(300) NOT NULL,
  `time` DATETIME NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`, `user_id`),
  INDEX `fk_post_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_post_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `civkac`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `civkac`.`follows`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `civkac`.`follows` ;

CREATE TABLE IF NOT EXISTS `civkac`.`follows` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `folows` INT NOT NULL,
  `user` INT NOT NULL,
  PRIMARY KEY (`id`, `folows`, `user`),
  INDEX `fk_user_has_user_user1_idx` (`user` ASC),
  INDEX `fk_user_has_user_user_idx` (`folows` ASC),
  CONSTRAINT `fk_user_has_user_user`
    FOREIGN KEY (`folows`)
    REFERENCES `civkac`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_user_has_user_user1`
    FOREIGN KEY (`user`)
    REFERENCES `civkac`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `civkac`.`reply`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `civkac`.`reply` ;

CREATE TABLE IF NOT EXISTS `civkac`.`reply` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `text` VARCHAR(300) NOT NULL,
  `time` VARCHAR(45) NOT NULL,
  `user_id` INT NOT NULL,
  `post_id` INT NOT NULL,
  PRIMARY KEY (`id`, `user_id`, `post_id`),
  INDEX `fk_reply_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_reply_post1`
    FOREIGN KEY (`post_id`)
    REFERENCES `civkac`.`post` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_reply_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `civkac`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `civkac`.`fileType`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `civkac`.`fileType` ;

CREATE TABLE IF NOT EXISTS `civkac`.`fileType` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `civkac`.`file`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `civkac`.`file` ;

CREATE TABLE IF NOT EXISTS `civkac`.`file` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `path` VARCHAR(45) NOT NULL,
  `fileType_id` INT NOT NULL,
  `post_id` INT NOT NULL,
  PRIMARY KEY (`id`, `fileType_id`, `post_id`),
  UNIQUE INDEX `path_UNIQUE` (`path` ASC),
  INDEX `fk_file_fileType1_idx` (`fileType_id` ASC),
  INDEX `fk_file_post1_idx` (`post_id` ASC),
  CONSTRAINT `fk_file_fileType1`
    FOREIGN KEY (`fileType_id`)
    REFERENCES `civkac`.`fileType` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_file_post1`
    FOREIGN KEY (`post_id`)
    REFERENCES `civkac`.`post` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `civkac`.`PostRating`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `civkac`.`PostRating` ;

CREATE TABLE IF NOT EXISTS `civkac`.`PostRating` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `post_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`, `post_id`, `user_id`),
  INDEX `fk_PostRating_post1_idx` (`post_id` ASC),
  INDEX `fk_PostRating_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_PostRating_post1`
    FOREIGN KEY (`post_id`)
    REFERENCES `civkac`.`post` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_PostRating_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `civkac`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `civkac`.`ReplyRating`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `civkac`.`ReplyRating` ;

CREATE TABLE IF NOT EXISTS `civkac`.`ReplyRating` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `reply_id` INT NOT NULL,
  PRIMARY KEY (`id`, `user_id`, `reply_id`),
  INDEX `fk_ReplyRating_user1_idx` (`user_id` ASC),
  INDEX `fk_ReplyRating_reply1_idx` (`reply_id` ASC),
  CONSTRAINT `fk_ReplyRating_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `civkac`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ReplyRating_reply1`
    FOREIGN KEY (`reply_id`)
    REFERENCES `civkac`.`reply` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `civkac`.`Report`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `civkac`.`Report` ;

CREATE TABLE IF NOT EXISTS `civkac`.`Report` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `reason` VARCHAR(400) NOT NULL,
  `reporter` INT NOT NULL,
  `reporte` INT NOT NULL,
  PRIMARY KEY (`id`, `reporter`, `reporte`),
  INDEX `fk_Report_user1_idx` (`reporter` ASC),
  INDEX `fk_Report_user2_idx` (`reporte` ASC),
  CONSTRAINT `fk_Report_user1`
    FOREIGN KEY (`reporter`)
    REFERENCES `civkac`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Report_user2`
    FOREIGN KEY (`reporte`)
    REFERENCES `civkac`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
